export default Routes = {
  OnboardingOne: "OnboardingOne",
  OnboardingTwo: "OnboardingTwo",
  OnboardingThree: "OnboardingThree",
  GetStarted: "GetStarted",
  Register: "Register",
  Verification: "Verification",
  Success: "Success",
  PatientSetup: "PatientSetup",
  Login: "Login",
  LoginVerification: "LoginVerification",
  ConfirmPassword: "ConfirmPassword",
  PasswordResetConfirmed: "PasswordResetConfirmed",
  Home: "Home",
  Medication: "Medication",
  AddMedication: "AddMedication",
  Insights: "Insights",
  Profile: "Profile",
  SetupTwo: "SetupTwo",
  addMed: {
    FirstScreen: "AddMedOne",
    SecondScreen: "AddMedTwo",
    ThirdScreen: "AddMedThree",
    FourthScreen: "AddMedFour",
  },
  docScreen: {
    Home: "Home",
    Patient: "Patient",
    AddMedication: "AddMedication",
    Insight: "Insight",
    Profile: "Profile",
    PatientProfile: "PatientProfile",
  },
};
